/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myprojectfinal.fivecrowns;

import java.util.ArrayList;

/**
 *
 * @author JesusOmar Leal
 */
public class VentanaFiveCrowns extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFiveCrowns
     */
    Mano mano;
    Mano mano2 = new Mano(5);
    Pila<Carta> barajaAux = new Pila<>();

    public VentanaFiveCrowns() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonGenerarMano = new javax.swing.JButton();
        TituloVentana = new javax.swing.JLabel();
        BarajaPrincipalTEXT = new javax.swing.JLabel();
        BarajaAuxiliarTEXT = new javax.swing.JLabel();
        botonReiniciarMano = new javax.swing.JButton();
        PaloCartaTEXT = new javax.swing.JLabel();
        NumeroTEXT = new javax.swing.JLabel();
        cartaBarajaOriginal1 = new javax.swing.JTextField();
        cartaBarajaOriginal2 = new javax.swing.JTextField();
        cartaBarajaOriginal3 = new javax.swing.JTextField();
        cartaBarajaOriginal4 = new javax.swing.JTextField();
        cartaBarajaOriginal5 = new javax.swing.JTextField();
        cartaBarajaOriginal6 = new javax.swing.JTextField();
        cartaBarajaOriginal8 = new javax.swing.JTextField();
        cartaBarajaOriginal7 = new javax.swing.JTextField();
        cartaBarajaOriginal9 = new javax.swing.JTextField();
        cartaBarajaOriginal10 = new javax.swing.JTextField();
        cartaBarajaAux1 = new javax.swing.JTextField();
        cartaBarajaAux2 = new javax.swing.JTextField();
        cartaBarajaAux3 = new javax.swing.JTextField();
        cartaBarajaAux4 = new javax.swing.JTextField();
        cartaBarajaAux5 = new javax.swing.JTextField();
        cartaBarajaAux6 = new javax.swing.JTextField();
        cartaBarajaAux7 = new javax.swing.JTextField();
        cartaBarajaAux8 = new javax.swing.JTextField();
        cartaBarajaAux9 = new javax.swing.JTextField();
        cartaBarajaAux10 = new javax.swing.JTextField();
        filtrarTrebol = new javax.swing.JButton();
        filtrarPicas = new javax.swing.JButton();
        filtrarDiamante = new javax.swing.JButton();
        filtrarCorazon = new javax.swing.JButton();
        filtrarJoker = new javax.swing.JButton();
        filtrarEstrella = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        botonGenerarMano.setText("Generar Cartas");
        botonGenerarMano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarManoActionPerformed(evt);
            }
        });

        TituloVentana.setBackground(new java.awt.Color(255, 255, 255));
        TituloVentana.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TituloVentana.setText("Five Crowns");

        BarajaPrincipalTEXT.setText("Baraja Principal");

        BarajaAuxiliarTEXT.setText("Baraja Auxiliar");

        botonReiniciarMano.setText("Reestablecer");
        botonReiniciarMano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarManoActionPerformed(evt);
            }
        });

        PaloCartaTEXT.setText("Palo Carta");

        NumeroTEXT.setText("Numero");

        cartaBarajaOriginal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaOriginal2ActionPerformed(evt);
            }
        });

        cartaBarajaOriginal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaOriginal3ActionPerformed(evt);
            }
        });

        cartaBarajaAux2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaAux2ActionPerformed(evt);
            }
        });

        cartaBarajaAux3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaAux3ActionPerformed(evt);
            }
        });

        cartaBarajaAux6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaAux6ActionPerformed(evt);
            }
        });

        cartaBarajaAux8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBarajaAux8ActionPerformed(evt);
            }
        });

        filtrarTrebol.setText("Trebol");
        filtrarTrebol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarTrebolActionPerformed(evt);
            }
        });

        filtrarPicas.setText("Picas");
        filtrarPicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarPicasActionPerformed(evt);
            }
        });

        filtrarDiamante.setText("Diamante");
        filtrarDiamante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDiamanteActionPerformed(evt);
            }
        });

        filtrarCorazon.setText("Corazon");
        filtrarCorazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarCorazonActionPerformed(evt);
            }
        });

        filtrarJoker.setText("Joker");
        filtrarJoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarJokerActionPerformed(evt);
            }
        });

        filtrarEstrella.setText("Estrella");
        filtrarEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarEstrellaActionPerformed(evt);
            }
        });

        b3.setText("3");

        b4.setText("4");

        b5.setText("5");

        b6.setText("6");

        b7.setText("7");

        b8.setText("8");

        b9.setText("9");

        b10.setText("10");

        b11.setText("J");

        b12.setText("Q");

        b13.setText("K");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloVentana)
                .addGap(317, 317, 317))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cartaBarajaAux1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cartaBarajaAux6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BarajaAuxiliarTEXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cartaBarajaAux3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cartaBarajaAux8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartaBarajaAux10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cartaBarajaOriginal1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cartaBarajaOriginal6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cartaBarajaOriginal8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cartaBarajaOriginal3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartaBarajaOriginal5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BarajaPrincipalTEXT))
                        .addGap(82, 82, 82)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonGenerarMano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonReiniciarMano, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumeroTEXT)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaloCartaTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(filtrarTrebol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filtrarPicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filtrarDiamante, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(filtrarEstrella, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filtrarCorazon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filtrarJoker, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(BarajaPrincipalTEXT)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartaBarajaOriginal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaOriginal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaOriginal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaOriginal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaOriginal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartaBarajaOriginal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cartaBarajaOriginal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cartaBarajaOriginal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cartaBarajaOriginal9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cartaBarajaOriginal10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartaBarajaAux2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartaBarajaAux6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBarajaAux10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonReiniciarMano)
                            .addComponent(botonGenerarMano))
                        .addGap(18, 18, 18)
                        .addComponent(PaloCartaTEXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtrarTrebol)
                            .addComponent(filtrarCorazon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtrarPicas)
                            .addComponent(filtrarEstrella))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtrarDiamante)
                            .addComponent(filtrarJoker)
                            .addComponent(BarajaAuxiliarTEXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumeroTEXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3)
                            .addComponent(b4)
                            .addComponent(b5)
                            .addComponent(b6)
                            .addComponent(b7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b8)
                            .addComponent(b9)
                            .addComponent(b10)
                            .addComponent(b11)
                            .addComponent(b12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b13)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarManoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarManoActionPerformed

        ArrayList<Carta> contenidoMano = new ArrayList<>();

        this.mano = new Mano(10);
        mano2.crearCopia(mano.getBaraja());

        contenidoMano = mano.extraerPila(mano.getBaraja());

        // System.out.println("" + contenidoMano);
        //BARAJA ORIGINAL IMPRESION
        cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
        cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

        cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
        cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

        cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
        cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

        cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
        cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

        cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
        cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

        cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
        cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

        cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
        cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

        cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
        cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

        cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
        cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

        cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
        cartaBarajaOriginal10.setText("" + contenidoMano.get(9));

    }//GEN-LAST:event_botonGenerarManoActionPerformed

    private void botonReiniciarManoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarManoActionPerformed
        barajaAux.clear();

        mano.crearCopia(mano2.getBaraja());
    }//GEN-LAST:event_botonReiniciarManoActionPerformed

    private void cartaBarajaOriginal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaOriginal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaOriginal2ActionPerformed

    private void cartaBarajaOriginal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaOriginal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaOriginal3ActionPerformed

    private void cartaBarajaAux2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaAux2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaAux2ActionPerformed

    private void cartaBarajaAux3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaAux3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaAux3ActionPerformed

    private void cartaBarajaAux6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaAux6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaAux6ActionPerformed

    private void cartaBarajaAux8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBarajaAux8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBarajaAux8ActionPerformed

    private void filtrarPicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarPicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarPicasActionPerformed

    private void filtrarDiamanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDiamanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarDiamanteActionPerformed

    private void filtrarCorazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarCorazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarCorazonActionPerformed

    private void filtrarJokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarJokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarJokerActionPerformed

    private void filtrarEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarEstrellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarEstrellaActionPerformed

    private void filtrarTrebolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarTrebolActionPerformed
        ArrayList<Carta> contenidoMano = new ArrayList<>();
        ArrayList<Carta> contenidoAux = new ArrayList<>();

        if (!mano.getBaraja().estaVacia()) {

            mano.filtrarPorPalo(1, barajaAux);

        } else {

            System.out.println("Ya no hay cartas");

        }

        contenidoMano = mano.extraerPila(mano.getBaraja());
        contenidoAux = mano.extraerPila(barajaAux);

        System.out.println("" + contenidoMano);
        System.out.println("" + barajaAux);

//BARAJA ORIGINAL IMPRESION
        switch (contenidoMano.size()) {

            case 0:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 1:
                 cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 2:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 3:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;

            case 4:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 5:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 6:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 7:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
            case 8:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));

                break;
            case 9:
                cartaBarajaOriginal1.setBackground(contenidoMano.get(0).obtenerColor(contenidoMano.get(0).getColor()));
                cartaBarajaOriginal1.setText("" + contenidoMano.get(0));

                cartaBarajaOriginal2.setBackground(contenidoMano.get(1).obtenerColor(contenidoMano.get(1).getColor()));
                cartaBarajaOriginal2.setText("" + contenidoMano.get(1));

                cartaBarajaOriginal3.setBackground(contenidoMano.get(2).obtenerColor(contenidoMano.get(2).getColor()));
                cartaBarajaOriginal3.setText("" + contenidoMano.get(2));

                cartaBarajaOriginal4.setBackground(contenidoMano.get(3).obtenerColor(contenidoMano.get(3).getColor()));
                cartaBarajaOriginal4.setText("" + contenidoMano.get(3));

                cartaBarajaOriginal5.setBackground(contenidoMano.get(4).obtenerColor(contenidoMano.get(4).getColor()));
                cartaBarajaOriginal5.setText("" + contenidoMano.get(4));

                cartaBarajaOriginal6.setBackground(contenidoMano.get(5).obtenerColor(contenidoMano.get(5).getColor()));
                cartaBarajaOriginal6.setText("" + contenidoMano.get(5));

                cartaBarajaOriginal7.setBackground(contenidoMano.get(6).obtenerColor(contenidoMano.get(6).getColor()));
                cartaBarajaOriginal7.setText("" + contenidoMano.get(6));

                cartaBarajaOriginal8.setBackground(contenidoMano.get(7).obtenerColor(contenidoMano.get(7).getColor()));
                cartaBarajaOriginal8.setText("" + contenidoMano.get(7));

                cartaBarajaOriginal9.setBackground(contenidoMano.get(8).obtenerColor(contenidoMano.get(8).getColor()));
                cartaBarajaOriginal9.setText("" + contenidoMano.get(8));

                cartaBarajaOriginal10.setBackground(contenidoMano.get(9).obtenerColor(contenidoMano.get(9).getColor()));
                cartaBarajaOriginal10.setText("" + contenidoMano.get(9));
                break;
        }
        /* //BARAJA Aux IMPRESION
        cartaBarajaAux1.setBackground(contenidoAux.get(0).obtenerColor(contenidoAux.get(0).getColor()));
        cartaBarajaAux1.setText("" + contenidoAux.get(0));

        cartaBarajaAux2.setBackground(contenidoAux.get(1).obtenerColor(contenidoAux.get(1).getColor()));
        cartaBarajaAux2.setText("" + contenidoAux.get(1));

        cartaBarajaAux3.setBackground(contenidoAux.get(2).obtenerColor(contenidoAux.get(2).getColor()));
        cartaBarajaAux3.setText("" + contenidoAux.get(2));

        cartaBarajaAux4.setBackground(contenidoAux.get(3).obtenerColor(contenidoAux.get(3).getColor()));
        cartaBarajaAux4.setText("" + contenidoAux.get(3));

        cartaBarajaAux5.setBackground(contenidoAux.get(4).obtenerColor(contenidoAux.get(4).getColor()));
        cartaBarajaAux5.setText("" + contenidoAux.get(4));

        cartaBarajaAux6.setBackground(contenidoAux.get(5).obtenerColor(contenidoAux.get(5).getColor()));
        cartaBarajaAux6.setText("" + contenidoAux.get(5));

        cartaBarajaAux7.setBackground(contenidoAux.get(6).obtenerColor(contenidoAux.get(6).getColor()));
        cartaBarajaAux7.setText("" + contenidoAux.get(6));

        cartaBarajaAux8.setBackground(contenidoAux.get(7).obtenerColor(contenidoAux.get(7).getColor()));
        cartaBarajaAux8.setText("" + contenidoAux.get(7));

        cartaBarajaAux9.setBackground(contenidoAux.get(8).obtenerColor(contenidoAux.get(8).getColor()));
        cartaBarajaAux9.setText("" + contenidoAux.get(8));

        cartaBarajaAux10.setBackground(contenidoAux.get(9).obtenerColor(contenidoAux.get(9).getColor()));
        cartaBarajaAux10.setText("" + contenidoAux.get(9));
         */
    }//GEN-LAST:event_filtrarTrebolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFiveCrowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFiveCrowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFiveCrowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFiveCrowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFiveCrowns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarajaAuxiliarTEXT;
    private javax.swing.JLabel BarajaPrincipalTEXT;
    private javax.swing.JLabel NumeroTEXT;
    private javax.swing.JLabel PaloCartaTEXT;
    private javax.swing.JLabel TituloVentana;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton botonGenerarMano;
    private javax.swing.JButton botonReiniciarMano;
    private javax.swing.JTextField cartaBarajaAux1;
    private javax.swing.JTextField cartaBarajaAux10;
    private javax.swing.JTextField cartaBarajaAux2;
    private javax.swing.JTextField cartaBarajaAux3;
    private javax.swing.JTextField cartaBarajaAux4;
    private javax.swing.JTextField cartaBarajaAux5;
    private javax.swing.JTextField cartaBarajaAux6;
    private javax.swing.JTextField cartaBarajaAux7;
    private javax.swing.JTextField cartaBarajaAux8;
    private javax.swing.JTextField cartaBarajaAux9;
    private javax.swing.JTextField cartaBarajaOriginal1;
    private javax.swing.JTextField cartaBarajaOriginal10;
    private javax.swing.JTextField cartaBarajaOriginal2;
    private javax.swing.JTextField cartaBarajaOriginal3;
    private javax.swing.JTextField cartaBarajaOriginal4;
    private javax.swing.JTextField cartaBarajaOriginal5;
    private javax.swing.JTextField cartaBarajaOriginal6;
    private javax.swing.JTextField cartaBarajaOriginal7;
    private javax.swing.JTextField cartaBarajaOriginal8;
    private javax.swing.JTextField cartaBarajaOriginal9;
    private javax.swing.JButton filtrarCorazon;
    private javax.swing.JButton filtrarDiamante;
    private javax.swing.JButton filtrarEstrella;
    private javax.swing.JButton filtrarJoker;
    private javax.swing.JButton filtrarPicas;
    private javax.swing.JButton filtrarTrebol;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
